### ISSUE TITLE
There is a TypeError saying URL is not a constructor, from gaxios dependency. Someone please help me.

### ISSUE THREAD

**Issue by ManojaD2004** [theoephraim/node-google-spreadsheet#688]
I have used google-auth-library, JWT auth for auth. Just yesterday it was working, today it is not.

https://theoephraim.github.io/node-google-spreadsheet/

Followed everything that was there in this docs. Also I’m using nextjs.

**Comment by gusintheeshell** [comment]
Same here, using Cypress

**Comment by nikfakel** [comment]
Same here, but problem with `google-auth-library`. It has dependency `gaxios` and invoke method https://github.com/googleapis/gaxios/blob/main/src/gaxios.ts#L191 with lowercase, but it should be uooercase. I changed it directly in node_modules and it works. Now we need to wait for fix from google

**Comment by v29neil** [comment]
Any update on this fix ?

**Comment by MrBadIvan** [comment]
Had the same issue, changed version to 9.7.0 and it works.
(thanks for the hint that the issue happened 3 weeks ago)

**Comment by TimKraemer** [comment]
> Same here. I found out that `google-auth-library` cause this problem. It has dependency `gaxios` and invoke method [googleapis/gaxios@`main`/src/gaxios.ts#L191](https://github.com/googleapis/gaxios/blob/main/src/gaxios.ts?rgh-link-date=2024-04-22T03%3A26%3A13Z#L191) with uppercase method URL, but it invoked in lowercase. I changed it directly in node_modules and it works. Now we need to wait for fix from google

@nikfakel  can you please describe what you changed directly in node_modules?

> Had the same issue, changed version to 9.7.0 and it works.


This doesn't fix it for me - @MrBadIvan did you do something extra except setting it to 9.7.0 and then npm / yarn install again? - I checked the `package.json` in node_modules and it's 9.7.0 but it's still creating the same Error.

**Comment by nikfakel** [comment]
@TimKraemer I changed this

-    const candidate = new url_1.URL(url);
+    const candidate = new url_1.Url(url);

And then I saved changes with patch-package, so CI/CD can keep this changes too

Now I got that this is no some bug, this package has to work on NodeJS and not considered to work in browser. So you can use just as is.

**Comment by MrBadIvan** [comment]
> did you do something extra except setting it to 9.7.0 and then npm / yarn install again?

Nope =/

**Comment by ManojaD2004** [comment]
Hey, I fixed it. Sorry for my late reply. 

Basically I just copied the code and ran it in nodejs, instead of client side javascript. And it worked perfectly. 👍

Note: I still managed to run this on nextjs, not on pages though, but in the form of an api.

**Comment by TimKraemer** [comment]
> @TimKraemer I changed this
> 
> * const candidate = new url_1.URL(url);
> 
> * const candidate = new url_1.Url(url);

Thank you! This is the only thing, that worked for me (I also had to remove my .next folder to kill the cached module).

**Comment by uzumis** [comment]
First of all. I tried to use patch-package to manage the error. But i dunno I'm using for Adobe Experience Manager purposes, but still having the gaxios URL typo.

Any updates of this issue?

**Comment by nikfakel** [comment]
@uzumis I use command (in package.json "scripts" to start server like this `"dev": "npx patch-package && next dev"`
before it I created patch with patch-package

**Comment by uzumis** [comment]
@nikfakel  Works like a charm.

before the patch package i use npm clean first to assure the patch will be applied with no problem.
My issue is solved for now. 
Thanks

**Comment by clare-lindley** [comment]
I've also experienced this and apart from directly hardcoding a fix in node_modules, I didn't know what else to do. I will try patching the package as you suggested @nikfakel.

I _did_ notice that it appeared to have been raised (and fixed?) already in this commit: https://github.com/googleapis/gaxios/pull/45/files#diff-1fbac0bfbd160f817d8a77140897b06cb53ff95f317bc9c3345afe4605fb3978

To fix it,  if you look at the top of `gaxios.ts` there are some helper functions to detect information about the environment in which it's running -it would be simple to add another similar function or maybe make use of `hasWindow()` to work out whether to use the node URL module or `window.url`.

Anyway, I thought about creating a pull request but I hesitated as it looked like it had at some point already been done - and maybe removed again for a reason?

**Comment by frama21** [comment]
same issue here, any update with this issue ?

**Comment by d-goog** [comment]
Fixing upstream in gaxios:
- https://github.com/googleapis/gaxios/pull/703

**Comment by theoephraim** [comment]
Closing as this seems to be resolved. Please re-open if still a problem.
